#!/bin/bash

FASTCGI_USER=www
FASTCGI_GROUP=www
SOCKET=/var/run/php-fastcgi.socket
PIDFILE=/var/run/php-fastcgi.pid
CHILDREN=6
PHP5=/usr/bin/php5-cgi

/usr/bin/spawn-fcgi -s $SOCKET -P $PIDFILE -C $CHILDREN -u $FASTCGI_USER -g $FASTCGI_GROUP -f $PHP5
